# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

butlers = Bio.create([{name: 'Geoffrey Butler' , url:" http://shinymedia.blogs.com/photos/uncategorized/joseph01.jpg" , content:"In addition to four years at the University of Oxford and a long career working for British aristocrats, Geoffrey was an Olympic runner several years before being hired by the Banks family, but fled his home country in shame after cheating in a race and being slapped by Queen Elizabeth II. His athletic failure seemed to have mixed adverse effects. Although disgraced in his native country of England, the British band Led Zeppelin hired him as their butler sometime in the 1970s. In the episode Nice Lady, besides telling Will he was a Greco-Roman wrestler, he had also worked for one British nobleman named Lord Balfour. Things came to a head when Lord Balfour paid Philip Banks a visit and Will was instructed to look after Lord Balfour's daughter Penelope. Sometime in the 1980s, Geoffrey got a job in the United States as a sparring partner for Chuck Norris, and also butlered for him. Presumably later he was hired to butler for the Banks family, where he worked for a long time. Although he shown signs of resentment at waiting on the Banks children and dealing with Will's boorish behavior, Geoffrey did seem to have a soft spot for Ashley Banks. He also shown a skill with women."},
{name: "Alfred Pennyworth", url:"http://static.comicvine.com/uploads/original/6/64137/3567589-batman_tas_alfred.jpeg" , content:"Alfred Thaddeus Crane Pennyworth is a fictional character appearing in American comic books published by DC Comics, most commonly in association with Batman. The character first appears in Batman #16 (April 1943), and was created by writers Bob Kane and Bill Finger, and artist Jerry Robinson. Alfred serves as a loyal, tireless butler who assists his employer's secret life as Batman. In modern interpretations, he is depicted as Bruce Wayne's butler, legal guardian, best friend, aide-de-camp, and surrogate parent following the murders of Thomas Wayne and Martha Wayne. He has sometimes been called Batman's batman.[1][2] He also provides comic relief, as his sometimes sarcastic and cynical attitude often adds humor to dialogue occurring between himself and Batman. A vital part of the Batman mythos, the character has been consistently popular over the years, having received a nomination for the R.A.C. Squiddy Award for Favorite Supporting Character in 1994 and for Best Character in 2001. Alfred was also nominated for the Wizard Fan Award for Favorite Supporting Male Character in 1994.[3] In non-comics media, the character has been portrayed by noted actors William Austin, Eric Wilton, Michael Gough, and Michael Caine on film and by Alan Napier, Efrem Zimbalist, Jr., Ian Abercrombie, and Sean Pertwee on television; Jeremy Irons will portray the character in his next film appearance."},
{name: "Mercy Graves", url:"https://hqrock.files.wordpress.com/2014/06/mercy-graves-cartoon-version.jpg" , content:"Mercedes 'Mercy' Graves III is a fictional character appearing in American comic books published by DC Comics. She debuted in 1996 on Superman: The Animated Series as the bodyguard and personal assistant of Superman's archenemy, Lex Luthor.[1] Like Harley Quinn and Livewire, she has since crossed over into comic books and is part of the DC Universe."},
{name: "Hobson", url: "http://4.bp.blogspot.com/-Zf7FWXYddE4/Tl_q3_v-njI/AAAAAAAAGEk/bW0P0swnNYM/s320/butler+13.jpg" , content:"Hosbon is serious. He has to take care of a belligerent drunk named Arthur."},
{name: "Wadsworth", url:"http://i2.wp.com/moviefail.com/wp-content/uploads/2014/10/curryclue.jpg" , content:"Always ever so neat and tidy with his buttling. He mentions to have been Mr. Boddy's former butler and that he had resigned after Mr. Boddy's blackmail had caused his wife to commit suicide (she had had socialist friends, which would've had dire consequences under the context of McCarthyism). There might be more to him however than there seems: in two of the endings he is an FBI agent, and in one of the endings, the character turns out to be the actual Mr. Boddy (and is eventually shot by Mr. Green in the hall with the revolver). Because he organized the whole gathering, he appoints himself as the de facto leader of the group."},
{name:"Peppermint Butler" , url:"http://img1.wikia.nocookie.net/__cb20100512224052/adventuretimewithfinnandjake/images/9/9e/Peppermint_Butler.png" , content:"He is an inhabitant of the Candy Kingdom who is involved with dark magic and also a loyal butler to Princess Bubblegum. Even though Princess Bubblegum lost her position as ruler of the Candy Kingdom to, the King of Ooo and moved away to a cabin near Lake Butterscotch, Peppermint Butler appears to still serve her as her butler. As is common with his occupation, Peppermint Butler is a well-dressed peppermint candy. He wears the traditional tailcoat of a butler, but opts for the less traditional blue version of the outfit. His shoes, gloves, and bow-tie are red, matching his red stripes; he also has white eyes."},
{name: "Duckworth", url: "http://wondersofdisney.yolasite.com/resources/toondis/ducktales/duckworth2.gif", content: "Scrooge's longtime, no-nonsense butler-chauffeur. Despite having Duck in his name, Duckworth is actually an anthropomorphic dog. He worked for Scrooge even before the nephews moved in. He is also Scrooge's chauffeur and errand boy on occasion. Duckworth used to be Scrooge's only household servant until Scrooge hired Mrs. Beakley. He usually appears as a supporting character. His only starring roles on the show are in the episode Duckworths Revolt and the episode-segment Take Me Out of the Ballgame.[1][2] He first appears in the first part of the pilot episode.[3] Duckworth is a jack-of-all-trades in the McDuck mansion, making him an important member of Scrooges staff."},
{name: "Lurch", url: "http://vignette1.wikia.nocookie.net/superfriends/images/9/98/Ted_-_Lurch_3.jpg/revision/latest?cb=20100620034944", content: "Lurch is a 6 ft 9 in (2.05 m) tall, shambling, gloomy butler who somewhat resembles a cross between Frankensteins monster (as played by Boris Karloff) and a zombie. On the Addams Family television series, Lurch has a deep, resonant voice unlike that of Herman Munster, a character on the show's main competitor, The Munsters. Although fully capable of normal speech, Lurch often communicates via simple inarticulate moans, which, much like the dialogue of Cousin Itt, his employers have no trouble understanding. The Addamses often comment that Lurch is eloquent and vivacious." } ])

images = Image.create([{url: "http://media1.break.com/breakstudios/2012/3/1/john-gielgud-arthur.jpg", caption:"Arthur made me look foolish"}, {url:"http://i1165.photobucket.com/albums/q591/northegreat/wadsworth.jpg", caption: "Get a CLUE"}, {url:"http://static.comicvine.com/uploads/scale_super/6/68997/1825066-scan0016.jpg", caption:"Don't mess with Alfred"}, {url:"https://bmj2k.files.wordpress.com/2013/07/tumblr_m4xiwqpsq01rw3b61o1_400.jpg", caption:"Remember this guy?"}])

posts = Post.create([{title: "I love tuxedos!", author: "Alfred", content: "I can't stop wearing this tuxedo! I look so snazzy in it"}])
posts = Post.create([{title: "I'm tired", author: "Jeeves", content: "Master Witherby won't stop making me scrub the toilets"}])
posts = Post.create([{title: "Limousine needs service", author: "Jenkins", content: "The limo is making a strange noise when I accelerate. Someone should take it in.  Maybe that someone should be me... nevermind"}])
posts = Post.create([{title: "Cat hair", author: "Wadsworth", content:"I will NO LONGER accept work in a house with cats, there is hair stuck in my cuff-links, it's EVERYWHERE"}])
